/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.wningram.financeapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;


@SpringBootApplication
public class App {
	
	@Value("${fixer.api.key}")
	private String fixerApiKey;

    public static void main(String[] args) {
		SpringApplication.run(App.class, args);
	}
    
    @Bean
    public CommandLineRunner run() {
		return _ -> {
			System.out.println(String.format("API Key is: %s", fixerApiKey));
		};
	}
}
