/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.wningram.financeapp;

import javax.swing.JFrame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public void initGui(String title, int width, int height) {
        JFrame mainFrame = new JFrame(title);
        mainFrame.setSize(width, height);

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
