/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.wningram.financeapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import com.github.wningram.financeapp.api.fixer.LatestRatesResponse;
import com.github.wningram.financeapp.api.fixer.client.FixerApiClient;
import com.github.wningram.financeapp.api.fixer.dto.Rate;

import reactor.core.publisher.Mono;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;


@SpringBootApplication
public class App {
	
	@Value("${fixer.api.key}")
	private String fixerApiKey;
	
	@Autowired
	private FixerApiClient fixerApiClient;

    public static void main(String[] args) {
		SpringApplication.run(App.class, args);
	}
    
    @Bean
    public CommandLineRunner run() {
		return args -> {
			if (args.length == 0) {
				System.out.println("No command provided. Available commands: print-api-key, get-latest-rates");
				return;
			}
			
			switch (args[0]) {
				case "print-api-key":
					System.out.println(String.format("API Key is: fixerApiKey"));
					break;
				case "get-latest-rates":
					// Example usage of FixerApiClient
					Mono<LatestRatesResponse> response = fixerApiClient.getLatestRates(null);
					response.map(ratesResponse -> {
						System.out.println(String.format("Base: %s, Date: %s", ratesResponse.getBase(), ratesResponse.getDate()));
						for (Rate rate : ratesResponse.getRates()) {
							System.out.println(String.format("Currency: %s, Rate: %s", rate.getCurrencyCode(), rate.getRate()));
						}
						return ratesResponse;
					});
					break;
			}
			
			return;
		};
	}
}
